[package]
name = "aoc2022"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
adventlib = { version = "0.1.0", path = "../adventlib" }
anyhow = "1.0.68"
